spring.application.name=rag-onebr
# Modelo de Embedding da OpenAI (muito barato e eficiente)
langchain4j.open-ai.embedding-model.api-key=sk-sua-chave-api-aqui
langchain4j.open-ai.embedding-model.model-name=text-embedding-3-small
